name: Setup SafeStream Project
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create all files
        run: python3 setup.py

      - name: Get gradle wrapper
        run: |
          mkdir -p gradle/wrapper
          curl -sL -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.4.0/gradle/wrapper/gradle-wrapper.jar

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Add all SafeStream project files"
          git push
